sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t git-etienico/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true git-etienico/docker-react npm run test -- --coverage
